---
title: "analysis-suburb"
author: "Brie Sherow"
date: "19/01/2021"
output: 
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
    df_print: paged
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data-setup}
# 0.1 Library load
lib.load = c("tidyverse","here", "ggplot2", "ggthemes", "treemap") 
lapply(lib.load, require, character.only = TRUE) 

# Check wd
here::here()

# Subfolders for project
# Data (holds .csv data) // # Original (holds original .xlxs)
# Output (holds output)

# Function -  Outersect
outersect <- function(x, y) {
  sort(c(setdiff(x, y),
         setdiff(y, x)))
}

# 0.2 Load data
load_codes = c("site", # contains site data 
               "event", # events per site
               "item",  # items per event
               "code")  # AMDI item codes

for(i in 1:length(load_codes)){
  
  fp = list.files(path = here("Data"), 
                  pattern = paste0(load_codes[i],".csv$"),
                  full.names = T)
  
  assign(paste0("df.",load_codes[i]), as.data.frame(read.csv(fp)))
  
}
```

```{r cleaning-data}
# 1.1 Pseudo-zero

# Summarise per item per event (remove item duplicates)
df.item = df.item %>% group_by(event_id,item) %>%
          summarise(total = sum(total)) %>%
          ungroup

# Split into list
ls.temp = split(df.item,f = df.item$event_id)

# Loop, id missing and add zero
ls.zeros = list()
for(i in 1:length(ls.temp)){
  
  #  (1)  Check which items are NOT present and create (2) df_absent
  item_absent = Reduce(outersect, list(df.code$item.ex, ls.temp[[i]]$item)) # (1)
  df.absent = data.frame(event_id = unique(ls.temp[[i]]$event_id),
                         item = item_absent,
                         total = 0) # (2)
  
  # c-bind w/ original   
  ls.zeros[[i]] = rbind(ls.temp[[i]],df.absent)
  
}
names(ls.zeros) = names(ls.temp)
df.item_zeros = bind_rows(ls.zeros)

# Remove items with all zeros or rare (less than 10)
item.keep = df.item_zeros %>% group_by(item)%>%
            summarise(total = sum(total)) %>%
            filter(total > 10)

# Final 'zeros' df
df.item_zeros = subset(df.item_zeros, df.item_zeros$item %in% item.keep$item)

# Clean
rm(df.absent, df.item, item.keep, ls.temp, ls.zeros, i, fp, item_absent)
```

```{r data-prep}
# Sub :: Merge -------------------------------------------------------------

    # 1.2 merge event per site
    df.event = df.event %>% dplyr::select(-event.wt,-event.tot) # Remove weight and total per event
    df.final = left_join(df.site,df.event, by = "Asset.ID")
    
    # 1.3 merge item per event
    df.final = left_join(df.final,df.item_zeros, by = "event_id")
    
    # 1.4 Add material and item type to df.final
    col.ind = grep("item.ex", names(df.code))
    df.final = left_join(df.final,df.code[,2:col.ind], by = c("item" = "item.ex"))
    
    # Remove 2 S.D.
    df.Qfinal = df.final %>% group_by(item) %>%
               summarise(Q3 = quantile(total,0.75), Q9 = quantile(total,0.9), 
                         avg = mean(total), sd = sd(total), max = max(total))
    
    df.Qfinal$sd2 = df.Qfinal$avg + 2*df.Qfinal$sd
      
    # Split by type
    ls.Qfinal = split(df.final, f = df.final$item) 
    item_name = unique(df.final$item) %>% sort() #ensure alphabetical
    
    ls.Qfilt = list()
    for(x in 1:length(item_name)){
      
      df.filt = df.final %>% filter(item == item_name[x]) %>% 
                filter(total < df.Qfinal$sd2[x])
      
      ls.Qfilt[[x]] = df.filt
      
    }
    
    names(ls.Qfilt) = item_name
    df.Qfilt = bind_rows(ls.Qfilt)
    
    rm(df.filt, df.item_zeros, df.final, ls.Qfilt, ls.Qfinal, item_name)
    
    # Remove items with all zeros [again]
    item.keep = df.Qfilt %>% group_by(item)%>%
                summarise(total = sum(total)) %>%
                filter(total != 0)
    
    # Final 'zeros' df
    df.Qfilt = subset(df.Qfilt, df.Qfilt$item %in% item.keep$item)
  
    
    # Graphing df (Choose group_by vars for graphing)
    # df.sum = df.Qfilt %>% group_by(LGA,item) %>% # CHANGE HERE
             # summarise(sum = sum(total), avg = mean(total), sd = sd(total)) 
    
    # Material
    # df.sum.mat = df.Qfilt %>% group_by(Land.use.zone,mat) %>% # CHANGE HERE
      # summarise(sum = sum(total), avg = mean(total), sd = sd(total)) 
  
    var_change = c("Rubber","Cloth", "Wood", "Glass & ceramic")
    df.Qfilt$mat[df.Qfilt$mat %in% var_change] = "Other"
    
```

```{r looping-maps}
# 2.0 Graphing ------------------------------------------------------------
    
LGA = unique(df.site$LGA) %>% as.character()
      
for(x in LGA){
  
#2.1 Define temp LGA
df.sum.mat = df.Qfilt %>% filter(LGA == x) %>%
             group_by(Land.use.zone,mat) %>% 
             summarise(sum = sum(total), avg = mean(total), sd = sd(total))

#2.11 Material by land use
p_sum <- ggplot(df.sum.mat, aes(x = reorder(mat, -sum), y = sum, fill = mat)) +
         geom_bar(stat="identity") +
         geom_text(aes(label = sum), vjust = -0.5, color = "black", size = 2) +
         facet_wrap(~Land.use.zone) +
         theme(axis.text.x = element_text(angle = 90)) +
         scale_y_continuous() +
         ggtitle("Sum of Material Types by Land Use", subtitle = x) +
         labs(y="Sum per material type (Counts)", x="Item Type")

 ggsave(filename = paste0(here("Output"),"/",x,"_mat_count.png"),
        plot = p_sum, dpi = 600)
  
#2.12 avg of material types by land use [leave out AVG for now] 
#   p_avg <- ggplot(df.sum.mat, aes(x=reorder(mat, -avg), y=avg, fill=mat)) +
#     geom_bar(stat="identity") +
#     scale_y_continuous() +
#     facet_wrap(~Land.use.zone) +
#     geom_errorbar(aes(ymin=0, ymax=avg+sd), width=.2,
#                   position=position_dodge(.9)) +
#     theme(axis.text.x = element_text(angle = 90)) +
#     ggtitle("Average of Material Types by Land Use", subtitle="Dandenong") + 
#     labs(y="Avg of Materials", x="Material Type")
#   
# p_avg

#2.13 Items by Land Use in Dandenong
df.sum = df.Qfilt %>% filter(LGA == x) %>%
         group_by(Land.use.zone,item) %>%
         summarise(sum = sum(total), avg = mean(total), sd = sd(total))  

top_LU <- df.sum %>% group_by(Land.use.zone) %>% top_n(5, sum) 

p_item_LU <- ggplot(top_LU, aes(x = reorder(item, -sum), y = sum, fill = item)) +
             geom_bar(stat="identity") +
             scale_y_continuous() +
             coord_cartesian() +
             facet_wrap(~Land.use.zone) +
             geom_text(aes(label = sum, vjust = -0.5), color = "black", size = 2) +
             theme(axis.text.x = element_blank()) +
             ggtitle("Top 5 items by Land Use", subtitle = x) +
             labs(y="Sum per material type (Counts)", x="Item Type")


 ggsave(filename = paste0(here("Output"),"/",x,"_item_count.png"),
        plot = p_item_LU, dpi = 600)

#2.14 Treemap of items in Dandenong
df.sum.item.mat = df.Qfilt %>% 
                  filter(LGA == x) %>%
                  group_by(Land.use.zone,mat,item) %>% 
                  summarise(sum = sum(total), avg = mean(total), sd = sd(total))

 png(filename = paste0(here("Output"),"/",x,"_tree.png"),width=800, height=800)
 
 tm_d_sum <- treemap(df.sum.item.mat,
                    index=c("mat","item"),  vSize="sum", type="index",
                    palette="Set3",
                    title= sprintf("Debris types in %s",x),
                    fontsize.title = 12,
                    fontsize.labels = c(12,10),
                    fontcolor.labels = c("black", "white"),
                    fontface.labels=c(2,1),
                    lowerbound.cex.labels = 1,
                    bg.labels=c("transparent"),
                    overlap.labels=0.1,
                    border.col=c("black", "white"),
                   border.lwds=c(7,2)
                   )
dev.off()

}
```


