---
title: "stats-tests"
author: "Brie Sherow"
date: "21/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(ggplot2) #graphing
library(ggthemes) #graphing templates
library(hrbrthemes) #graphing templates
library(lubridate) #date manipulation
library(forcats) #working with factors
library(tidyverse) #manipulating data
library(knitr) #rmarkdown functions
library(kableExtra) #table layouts
library(stats) #base R stats
library(broom) #create summaries from stats objects
library(car) #lm regression
library(MASS) #stats
library(lme4) #glmer function
library(DHARMa) #model verification
library(glmmTMB) #fit zero-inflated negative binomial
library(reshape2) #melt long to wide
library(Rcpp) #something to do with reshape
library(emmeans) #pairwise comparisons
```

# create df

```{r create-df, warning=FALSE, message=FALSE, results='hide', include=FALSE}
#create survey count  

        #load item counts
        item <- read.csv(file="Data/2101_item.csv", 
                         header=T, sep=",") 

#remove duplicate entries
        item <- unique(item[!duplicated(item),])

        #load item labels
        item_label <- read.csv(file="Data/item_label.csv", 
                         header=T, sep=",") 
        
        #load events
        event <- read.csv(file="Data/2101_event.csv", 
                         header=T, sep=",") 
        
        #join event info to item count
        survey_count <- left_join(item, event, by="event_id")
        
        survey_count <- survey_count %>%
          dplyr::select(-event.tot, -event.wt, -vol, -hr, -event_date, -note) %>%
          filter(item!="Pollution Rating") 

        #summarise duplicate survey entries (this will lose one set of notes....)
        item_merge <- survey_count %>%
          group_by(event_id, item) %>%
          summarise(sum=sum(total)) %>%
         ungroup()

        #join survey count to the merged summaries
        survey_count <- item_merge %>%
          left_join(survey_count, by=c("event_id"="event_id", "item"="item")) %>%
          dplyr::select(-total) %>%
          unique()
        
#create abundance data with all possible debris items and zero values

      # #count of items per unique event
      # event_count <- survey_count %>%
      #   group_by(event_id, item) %>%
      #   summarise(sum=sum(sum)) %>%
      #   ungroup()

      #load AMDI code\
      AMDI_code <- read.csv(file="Data/200101_AMDI_code.csv", 
                       header=T, sep=",") 
      
      #create full list of possible items
      AMDI <- AMDI_code %>%
        filter(item_code_id != "LSTD1") %>% #remove pollution rating / microplastics
        dplyr::select(item.ex, mat) #column of all possible item types
      
      
      #create a df of all possible items at all survey events, complete with zeros
      abund <- full_join(AMDI, survey_count, by=c("item.ex" = "item"))
      
      #data long to wide
      abund_wide <- abund %>%
        spread(item.ex, sum) %>%
        dplyr::select(-Asset.ID, -Cycle, -covid, -date, -mat)
      
      #replace na values with 0
      abund_wide[is.na(abund_wide)] <- 0
        
      #transform back to long but now with the full items list and zero data
      abund_long <- melt(abund_wide, id.vars="event_id")
      
      #remove the zero event ID (how did that get there?)
      abund_long <- abund_long[abund_long$event_id != 0, ]

#join abundance data to survey notes and other columns
      df <- left_join(abund_long, event, by="event_id")
      
        #load sites
          site <- read.csv(file="Data/200619_site.csv", 
                           header=T, sep=",") 
      
            #join LGA and luz to df
          df <- left_join(df, site, by = "Asset.ID")
          
          #classify items correctly      
           df <- df %>%
        dplyr::select(-event_date, -event.tot, -event.wt, -vol, -hr, 
                      -Site, -Latitude, -Longitude) %>% #remove duplicate columns
        rename(item=variable, #rename columns
               sum=value,
               asset_id = Asset.ID,
               cycle=Cycle,
               LUZ = Land.use.zone) %>% 
        mutate(asset_id=as.factor(asset_id), #classify columns correctly  
             item=as.factor(item),
             LGA=as.factor(LGA),
             LUZ=as.factor(LUZ),
             event_id=as.factor(event_id),
             cycle=as.factor(cycle),
             date=dmy(date)
             )

#resolve duplicates in MC01, C5    
          dup <- df %>% 
            group_by(asset_id, cycle, item) %>% #reconcile duplicates in MC01 Cycle 5
            summarise(sum=sum(sum)) %>%
            ungroup()
           
      # #check difference
      #      subsetdf <- df %>%
      #        dplyr::select(Asset.ID, Cycle, item, sum)
      #      
      #      setdiff(subsetdf, dup)
           
      #join C5 correction to df
      df <- dup %>% left_join(df, by=c("asset_id"="asset_id", 
                                       "cycle"="cycle", "item"="item")) %>%
        dplyr::select(-sum.y) %>%
        filter(event_id != "23097") %>%
        rename(sum = sum.x) %>%
        distinct()
      
      item_labelDF <- df %>%
        distinct(item)
      
      df <- df %>%
        left_join(item_label, by=c("item" = "item.type")) %>%
        mutate(item = A3) %>%
        dplyr::select(-A3)
      
#classify columns correctly    
      df <- df %>%
      mutate(item=as.factor(item),
             covid=as.factor(covid),
             material=as.factor(material))

#Combine C8 and C9    
     #isolate C8
    C8 <- df %>%
      filter(cycle == "C8")
    
    #isolate C9
    C9 <- df %>%
      filter(cycle == "C9")
    
    #join C8 and C9 by unique drain and item to capture double surveys
    t <- left_join(C9, C8, by=c("asset_id"="asset_id", "item" = "item"))
    t$sum.y[is.na(t$sum.y)] <- 0 #change na to 0
    
    t <- t %>%
      mutate(combined_sum = sum.y + sum.x) %>% #add C8 and C9 together
      dplyr::select(event_id.x, item, combined_sum)
    
    df <- df %>% 
      left_join(t, by = c("event_id"="event_id.x", "item"="item")) %>%
      filter(cycle != "C8") %>%
      mutate(combined_sum = tidyr::replace_na(combined_sum, 0),
              sum2 = ifelse(cycle != "C9", sum, 0),
              final_sum = sum2 + combined_sum) %>%
      dplyr::select(-sum2, -sum, -combined_sum) %>%
      rename(sum = final_sum)
    
#find days since last survey at each asset
diff <- df %>%
  distinct(event_id, .keep_all = T) %>%
  dplyr::select(-item,-sum) %>%
  group_by(asset_id) %>% #looking at each event
  arrange(date) %>%
  mutate(days = date - lag(date)) %>% #days since last survey event
  filter(days != "NA") %>% #remove first survey date
  ungroup()

unique(diff$days)

diff_red <- diff %>% dplyr::select(event_id, asset_id, days)

df <- df %>%
  left_join(diff_red, by="event_id") %>%
  dplyr::select(-asset_id.y) %>%
  rename(asset_id = asset_id.x)
    
```

# total

```{r drop1-total}

 mod = df %>% 
    group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
    summarise(sum=sum(sum)) %>%
    ungroup() %>%
    mutate(LGA = as.factor(LGA),
           LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
           covid = as.factor(covid),
           cycle = droplevels(as.factor(cycle)))
 
 #create model
 m  <- glmmTMB(sum ~ #Debris count per survey event
                   LUZ * covid + #predicted by land use effected by covid
                   (1|LGA/asset_id) + (1|cycle), #suburb random effect
                   family=nbinom2(), #negative binomial to deal with count data and zeros
                   data = mod)
 
 drop1_tot <- drop1(m, test="Chisq")
 
 drop1_tot
#           Df    AIC    LRT  Pr(>Chi)    
# <none>       9079.4                     
# LUZ:covid  3 9106.1 32.651 3.815e-07 ***
write.csv(drop1_tot,"d1_tot.csv", row.names = T)

```

```{r model-verification-total}
#create df
 mod = df %>% 
    group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
    summarise(sum=sum(sum)) %>%
    ungroup() %>%
    mutate(LGA = as.factor(LGA),
           LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
           covid = as.factor(covid),
           cycle = droplevels(as.factor(cycle)))

#create model
 m  <- glmmTMB(sum ~ #Debris count per survey event
                   LUZ * covid + #predicted by land use effected by covid
                   (1|LGA/asset_id) + (1|cycle), #suburb random effect
                   family=nbinom2(), #negative binomial to deal with count data and zeros
                   data = mod)
 
so_tot <- simulateResiduals(fittedModel = m, plot=T)
  
plotResiduals(so_tot)
testUniformity(so_tot) #tests if the overall distribution conforms to expectations
testOutliers(so_tot) #tests if there are more simulation outliers than expected
testDispersion(so_tot) #tests if the simulated dispersion is equal to the observed dispersion
testQuantiles(so_tot) #fits a quantile regression or residuals against a predictor (default predicted value), and tests of this conforms to the expected quantile
testZeroInflation(so_tot) #tests if there are more zeros than expected

              gsum_tot <- summary(m)
              gsum_tot <- as.data.frame(gsum_tot$coefficients$cond)
              gsum_tot$item = "Total"
              gsum_tot$model = "interaction"
              
write.csv(gsum_tot,"gsum_tot.csv", row.names = T)
```
```{r temporal-autocorrelation-total}
mod$resid = resid(m) #create a column for each survey event's residuals

mod_temp <- mod %>%
    group_by(date) %>%
    summarise(sum=sum(resid))

testTemporalAutocorrelation(mod_temp$sum, 
                              time =  mod_temp$date) #test resid for temporal autocorrelation
```
```{r emmeans-total}
#create model for total debris
 mod = df %>% 
    group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
    summarise(sum=sum(sum)) %>%
    ungroup() %>%
    mutate(LGA = as.factor(LGA),
           LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
           covid = as.factor(covid),
           cycle = droplevels(as.factor(cycle)))
 
 #create model
 m  <- glmmTMB(sum ~ #Debris count per survey event
                   LUZ * covid + #predicted by land use effected by covid
                   (1|LGA/asset_id) + (1|cycle), #suburb random effect
                   family=nbinom2(), #negative binomial to deal with count data and zeros
                   data = mod)

em_tot_1 <- emmeans(m, pairwise~covid|LUZ, type="response",level=0.95, infer=T)
em_tot_2 <- emmeans(m, pairwise~LUZ|covid, type="response",level=0.95, infer=T)

em_tot_cl <- summary(em_tot_1$contrasts)
em_tot_cl$item = "Total"

em_tot_lc <- summary(em_tot_2$contrasts)
em_tot_lc$item = "Total"
              
write.csv(em_tot_lc,"elc_tot.csv", row.names = T)
write.csv(em_tot_cl,"ecl_tot.csv", row.names = T)

```
# items

```{r drop-levels-item}

#create vector of items to test
          #find top 15 items
          top15 <- df %>%
            filter(item != "Metal scrap") %>% #removing outlier entry
            group_by(item) %>%
            summarise(sum=sum(sum)) %>%
            arrange(desc(sum)) %>%
            top_n(15, sum)
            
          #create vector from top 15 items
          top15 <- top15$item 
          top15 <- unlist(top15)
          
          #items of policy interest
          pol_items <- df %>% 
            filter(item == "OH & S" | item=="Aluminium cans" | item == "Foam take-away")
          
          #create vector from policy items
          pol_items <- pol_items$item 
          pol_items <- unlist(pol_items)
          
          #vector of all items of interest due to abundance or policy relevance
          top_txt<- df %>%
            filter(item %in% top15 | item %in% pol_items) %>%
            distinct(item)%>%
            pull(item) %>% 
            droplevels()
  
# Purrr to determine interaction between covid and luz
              d1_item_int = purrr::map_df(top_txt, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public   Transport Terminal", "Industrial Precinct")),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ * covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              d <- drop1(m_temp, test="Chisq")
              
                #create dataframe to determine if interaction effect is significant
              d <- d %>%
                filter(LRT != "NA") %>%
                rename(p.value = 'Pr(>Chi)')
              
              d$item = x
              d$model = "interaction"
              
              return(d)
              
               })
          
          d1_item_int
          write.csv(d1_item_int,"d1_item_int.csv", row.names = T)
          
#create vectors for items where interaction is significant or not
          
        #vector of items where covid and luz interaction is significant
        d_int_vec <- d1_item_int %>%
          filter(p.value < 0.05) %>%
          distinct(item)%>%
          pull(item) %>% 
          droplevels()
    
        #vector of items where covid * luz is not significant
        d_main_vec <- d1_item_int %>%
          filter(p.value>0.05) %>%
          distinct(item)%>%
          pull(item) %>% 
          droplevels()
    
# Purrr to determine main effects of covid and luz
            d1_item_main = purrr::map_df(d_main_vec, function(x){
              
              temp_df = df %>% 
                filter(item == paste0(x)) %>%
                group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
                summarise(sum=sum(sum)) %>%
                ungroup() %>%
                mutate(LGA = as.factor(LGA),
                       LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                       covid = as.factor(covid),
                       cycle = droplevels(as.factor(cycle)),
                       item = x)
             
             #create model
             m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                               LUZ + covid + #predicted by land use effected by covid
                               (1|LGA/asset_id) + (1|cycle), #suburb random effect
                               family=nbinom2(), #nbinom to deal with count data and zeros
                               data = temp_df)
             
            d <- drop1(m_temp, test="Chisq")
            d <- d %>%
                filter(LRT != "NA") %>%
                rename(p.value = 'Pr(>Chi)')
            d$item = x
            d$model = "main"
            
            return(d)
            
             })
            
            d1_item_main
            write.csv(d1_item_main,"d1_item_main.csv", row.names = T)
            
# Purrr to determine main effect of covid
            d1_item_cov = purrr::map_df(d_main_vec, function(x){
              
              temp_df = df %>% 
                filter(item == paste0(x)) %>%
                group_by(event_id, asset_id, cycle, date, covid, LGA) %>% #relevant variables
                summarise(sum=sum(sum)) %>%
                ungroup() %>%
                mutate(LGA = as.factor(LGA),
                       covid = as.factor(covid),
                       cycle = droplevels(as.factor(cycle)),
                       item = x)
             
             #create model
             m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                               covid + #predicted by land use effected by covid
                               (1|LGA/asset_id) + (1|cycle), #suburb random effect
                               family=nbinom2(), #nbinom to deal with count data and zeros
                               data = temp_df)
             
            d <- drop1(m_temp, test="Chisq")
            d <- d %>%
                filter(LRT != "NA") %>%
                rename(p.value = 'Pr(>Chi)')
            d$item = x
            d$model = "covid"
            
            return(d)
            
             })
            
            d1_item_cov
            write.csv(d1_item_cov,"d1_item_cov.csv", row.names = T)
            
# Purrr to determine main effects of luz
            d1_item_luz = purrr::map_df(d_main_vec, function(x){
              
              temp_df = df %>% 
                filter(item == paste0(x)) %>%
                group_by(event_id, asset_id, cycle, date, LGA, LUZ) %>% #relevant variables
                summarise(sum=sum(sum)) %>%
                ungroup() %>%
                mutate(LGA = as.factor(LGA),
                       LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                       cycle = droplevels(as.factor(cycle)),
                       item = x)
             
             #create model
             m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                               LUZ + #predicted by land use effected by covid
                               (1|LGA/asset_id) + (1|cycle), #suburb random effect
                               family=nbinom2(), #nbinom to deal with count data and zeros
                               data = temp_df)
             
            d <- drop1(m_temp, test="Chisq")
            d <- d %>%
                filter(LRT != "NA") %>%
                rename(p.value = 'Pr(>Chi)')
            d$item = x
            d$model = "luz"
            
            return(d)
            
             })
            
            d1_item_luz
            write.csv(d1_item_luz,"d1_item_luz.csv", row.names = T)
            
#vector of items where covid is significant
        d_cov_vec <- d1_item_cov %>%
          filter(p.value<0.05) %>%
          distinct(item)%>%
          pull(item) %>% 
          droplevels()
        
#vector of items where luz is significant
        d_luz_vec <- d1_item_luz %>%
          filter(p.value<0.05) %>%
          distinct(item)%>%
          pull(item) %>% 
          droplevels()

```

# Interaction model
```{r model-verification-int}
so_item_int = purrr::map_df(d_int_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ,
                    "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ * covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              so <- simulateResiduals(fittedModel = m_temp, plot=T)
              
              return(so)
              
               })
        
```

```{r summary-int}
 gsum_int = purrr::map_df(d_int_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public   Transport Terminal", "Industrial Precinct")),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ * covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
               g <- summary(m_temp)
               g <- as.data.frame(g$coefficients$cond)
              
              g$item = x
              g$model = "interaction"
              
              return(g)
               })

gsum_int
write.csv(gsum_int,"gsum_int.csv", row.names = T)
```

```{r emmeans-cl-int}

 ecl_int = purrr::map_df(d_int_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public   Transport Terminal", "Industrial Precinct")),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ * covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              e <- emmeans(m_temp, pairwise~covid|LUZ, type="response",level=0.95, infer=T)
               
              e <- summary(e$contrasts)
              e$item = x
              e$model = "interaction"
          
              
              return(e)
               })

write.csv(ecl_int,"ecl_int.csv", row.names = T)

```


```{r emmeans-lc-int}

 elc_int = purrr::map_df(d_int_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ * covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              e <- emmeans(m_temp, pairwise~LUZ|covid, type="response",level=0.95, infer=T)
               
              e <- summary(e$contrasts)
              e$item = x
              e$model = "interaction"
          
              
              return(e)
               })

write.csv(elc_int,"elc_int.csv", row.names = T)

```

# Main effect model
```{r model-verification-main}

# foil debris
          mod_foil = df %>% 
            filter(item == "Foil (including bladders)") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_foil  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_foil)
           
          so_foil <- simulateResiduals(fittedModel = m_foil, plot=T)


# hard plastic remnants debris
          mod_hplasrem = df %>% 
            filter(item == "Hard plastic remnants") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_hplasrem  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_hplasrem)
           
          so_hplasrem <- simulateResiduals(fittedModel = m_hplasrem, plot=T)
```
```{r summary-main}
# foil debris
          mod_foil = df %>% 
            filter(item == "Foil (including bladders)") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_foil  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_foil)
           
           gsum_foil <- summary(m_foil)
              gsum_foil <- as.data.frame(gsum_foil$coefficients$cond)
              
              gsum_foil$item = "Foil (including bladders)"
              gsum_foil$model = "main"
           
          


# hard plastic remnants debris
          mod_hplasrem = df %>% 
            filter(item == "Hard plastic remnants") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_hplasrem  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_hplasrem)
           
           gsum_hplasrem <- summary(m_hplasrem)
              gsum_hplasrem <- as.data.frame(gsum_hplasrem$coefficients$cond)
              
              gsum_hplasrem$item = "Hard plastic remnants"
              gsum_hplasrem$model = "main"
              
      gsum_main <- rbind(gsum_foil, gsum_hplasrem)
      
      gsum_main
      write.csv(gsum_main,"gsum_main.csv", row.names = T)
```

```{r em-cl-main}
# foil debris
          mod_foil = df %>% 
            filter(item == "Foil (including bladders)") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_foil  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_foil)
           
              e_cl_foil <- emmeans(m_foil, pairwise~covid|LUZ, type="response",level=0.95, infer=T)
               
              e_cl_foil <- summary(e_cl_foil$contrasts)
              e_cl_foil$item = "Foil (including bladders)"
              e_cl_foil$model = "main"
           
          


# hard plastic remnants debris
          mod_hplasrem = df %>% 
            filter(item == "Hard plastic remnants") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_hplasrem  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_hplasrem)
           
              e_cl_hplasrem <- emmeans(m_hplasrem, pairwise~covid|LUZ, type="response",level=0.95, infer=T)
               
              e_cl_hplasrem <- summary(e_cl_hplasrem$contrasts)
              e_cl_hplasrem$item = "Hard plastic remnants"
              e_cl_hplasrem$model = "main"
              
      ecl_main <- rbind(e_cl_foil, e_cl_hplasrem)
      
      ecl_main
      write.csv(ecl_main,"ecl_main.csv", row.names = T)
```
```{r em-lc-main}
# foil debris
          mod_foil = df %>% 
            filter(item == "Foil (including bladders)") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_foil  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_foil)
           
              e_lc_foil <- emmeans(m_foil, pairwise~LUZ|covid, type="response",level=0.95, infer=T)
               
              e_lc_foil <- summary(e_lc_foil$contrasts)
              e_lc_foil$item = "Foil (including bladders)"
              e_lc_foil$model = "main"
           
          


# hard plastic remnants debris
          mod_hplasrem = df %>% 
            filter(item == "Hard plastic remnants") %>%
              group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>% #relevant variables
              summarise(sum=sum(sum)) %>%
              ungroup() %>%
              mutate(LGA = as.factor(LGA),
                     LUZ = as.factor(
                       fct_relevel(LUZ, "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                     covid = as.factor(covid),
                     cycle = droplevels(as.factor(cycle)))
           
           #create model
           m_hplasrem  <- glmmTMB(sum ~ #Debris count per survey event
                             LUZ + covid + #predicted by land use effected by covid
                             (1|LGA/asset_id) + (1|cycle), #suburb random effect
                             family=nbinom2(), #negative binomial to deal with count data and zeros
                             data = mod_hplasrem)
           
              e_lc_hplasrem <- emmeans(m_hplasrem, pairwise~LUZ|covid, type="response",level=0.95, infer=T)
               
              e_lc_hplasrem <- summary(e_lc_hplasrem$contrasts)
              e_lc_hplasrem$item = "Hard plastic remnants"
              e_lc_hplasrem$model = "main"
              
      elc_main <- rbind(e_lc_foil, e_lc_hplasrem)
      
      elc_main
      write.csv(elc_main,"elc_main.csv", row.names = T)
```


# Covid model

```{r model-verification-cov}
so_item_cov = purrr::map_df(d_cov_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              so <- simulateResiduals(fittedModel = m_temp, plot=T)
              
              return(so)
              
               })
        
```
```{r summary-cov}
 gsum_cov = purrr::map_df(d_cov_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
                g <- summary(m_temp)
                g <- as.data.frame(g$coefficients$cond)
              
              g$item = x
              g$model = "covid"
              
              return(g)
               })

gsum_cov
write.csv(gsum_cov,"gsum_cov.csv", row.names = T)
```


```{r emmeans-cov}

 ecov = purrr::map_df(d_cov_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        covid = as.factor(covid),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 covid + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              e <- emmeans(m_temp, pairwise~covid, type="response",level=0.95, infer=T)
               
              e <- summary(e$contrasts)
              e$item = x
              e$model = "covid"
          
              
              return(e)
               })

write.csv(ecov,"ecov.csv", row.names = T)

```

# land use model
```{r model-verification-luz}
so_item_luz = purrr::map_df(d_luz_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ,
                    "CBD", "Shopping Centre", "Public Transport Terminal", "Industrial Precinct")),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              so <- simulateResiduals(fittedModel = m_temp, plot=T)
              
              return(so)
              
               })
        
```

```{r summary-luz}
 gsum_luz = purrr::map_df(d_luz_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public   Transport Terminal", "Industrial Precinct")),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              g <- summary(m_temp)
               g <- as.data.frame(g$coefficients$cond)
              
              g$item = x
              g$model = "luz"
              
              return(g)
               })

gsum_luz
write.csv(gsum_luz,"gsum_luz.csv", row.names = T)
```


```{r emmeans-luz}

 eluz = purrr::map_df(d_luz_vec, function(x){
                
                temp_df = df %>% 
                  filter(item == paste0(x)) %>%
                  group_by(event_id, asset_id, cycle, date, covid, LGA, LUZ) %>%
                  summarise(sum=sum(sum)) %>%
                  ungroup() %>%
                  mutate(LGA = as.factor(LGA),
                        LUZ = as.factor(fct_relevel(LUZ, "CBD", "Shopping Centre", "Public   Transport Terminal", "Industrial Precinct")),
                        cycle = droplevels(as.factor(cycle)),
                        item = x)
               
               #create model
               m_temp  <- glmmTMB(sum ~ #Debris count per survey event
                                 LUZ + #predicted by land use effected by covid
                                 (1|LGA/asset_id) + (1|cycle), #suburb random effect
                                 family=nbinom2(), #nbinom to deal with count data and zeros
                                 data = temp_df)
               
              e <- emmeans(m_temp, pairwise~LUZ, type="response",level=0.95, infer=T)
               
              e <- summary(e$contrasts)
              e$item = x
              e$model = "luz"
          
              
              return(e)
               })

write.csv(eluz,"eluz.csv", row.names = T)

```






